{{
    const utils = require('./utils.js');
    // console.log("Utils loaded successfully");

    today = utils.date.timestampToLocalISO(utils.date.getStartOfToday());
    tomorrow = utils.date.timestampToLocalISO(utils.date.getEndOfTomorrow());

    exports.today = today;
    exports.tomorrow = tomorrow;
}}

###

# @no-cookie-jar
GET {{GATSBY_API_BASE_URL}}/availability/classes?max=15&minDate={{today}}&maxDate={{tomorrow}}&timezone=America/Los_Angeles
Authorization: Basic {{API_USER_ID}}:{{API_KEY}}